name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, production ]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
